server:
  port: 8760
  netty:
    connection-timeout: 10000
    idle-timeout: 10000
    threads: 3000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        pool:
          type: elastic
          max-idle-time: 10000
          max-connections: 5000
          max-life-time: 10000
        connect-timeout: 10000
        response-timeout: 30000
        max-header-size: 875000
      metrics:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/api/product/v3/api-docs

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/api/order/v3/api-docs

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: inventory-service-docs
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/v3/api-docs

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info


service:
  swagger:
    version: 'version1.0.0-1403/03/30'
    title: 'api gateway'
    description: 'api gateway'

springdoc:
  swagger-ui:
    display-request-duration: true
    display-operation-id: true
    tags-sorter: alpha
    path: /swagger-ui.html
    urls:
      - url: http://localhost:${server.port}/api/product/v3/api-docs
        name: 'product service'
      - url: http://localhost:${server.port}/api/order/v3/api-docs
        name: 'order service'
      - url: http://localhost:${server.port}/api/inventory/v3/api-docs
        name: 'inventory service'
  api-docs:
    groups:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
