server:
  port: 8761
  tomcat:
    accesslog:
      enabled: true
      encoding: UTF-8
    connection-timeout: 10000
    max-connections: 10000
    threads:
      max: 3000
      min-spare: 100

spring:
  application:
    name: discovery-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  instance:
    appname: ${spring.application.name}
    hostname: localhost


management:
  zipkin:
    tracing:
      connect-timeout: 10000
      encoding: json
      read-timeout: 10000
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'