server:
  port: 9600
  tomcat:
    accesslog:
      enabled: true
      encoding: UTF-8
    connection-timeout: 10000
    max-connections: 10000
    threads:
      max: 3000
      min-spare: 100

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      username: saber66
      password: AdminSaber66
      port: 27017
      database: mydb

service:
  baseUrl: "/api/product"
  swagger:
    version: 'version1.0.0-1403/03/26'
    title: 'product service'
    description: 'product service'
  api-gateway:
    host: localhost
    port: 8760

springdoc:
  swagger-ui:
    display-request-duration: true
    display-operation-id: true
    tags-sorter: alpha
    path: /swagger-ui.html
  #    oauth:
  #      app-name: saber-client
  #      client-id: saber-client
  #      realm: saber66
  #      client-secret: 73b6e1da-d0ef-474c-97ae-d1c4438a7535
  #      scopes:
  #        - "openid"
  #        - "read"
  #        - "write"
  #      tags-sorter: alpha
  oAuthFlow:
    authorizationUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/auth
    tokenUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true


  api-docs:
    path: ${service.baseUrl}/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}

management:
  zipkin:
    tracing:
      connect-timeout: 10000
      encoding: json
      read-timeout: 10000
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'